---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app
  namespace: sample-app-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sample-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: production/sample-app
        property: database_url
