---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-app

resources:
  - namespace.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: kubernetes-devops-template
      app.kubernetes.io/managed-by: kustomize
